/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import { PublicKey } from '@metaplex-foundation/umi';
import {
  Serializer,
  i64,
  publicKey as publicKeySerializer,
  struct,
  u64,
} from '@metaplex-foundation/umi/serializers';

export type Lockup = {
  unixTimestamp: bigint;
  epoch: bigint;
  custodian: PublicKey;
};

export type LockupArgs = {
  unixTimestamp: number | bigint;
  epoch: number | bigint;
  custodian: PublicKey;
};

export function getLockupSerializer(): Serializer<LockupArgs, Lockup> {
  return struct<Lockup>(
    [
      ['unixTimestamp', i64()],
      ['epoch', u64()],
      ['custodian', publicKeySerializer()],
    ],
    { description: 'Lockup' }
  ) as Serializer<LockupArgs, Lockup>;
}
