/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import { Serializer, struct, u64 } from '@metaplex-foundation/umi/serializers';
import {
  Authorized,
  AuthorizedArgs,
  Lockup,
  LockupArgs,
  getAuthorizedSerializer,
  getLockupSerializer,
} from '.';

export type Meta = {
  rentExemptReserve: bigint;
  authorized: Authorized;
  lockup: Lockup;
};

export type MetaArgs = {
  rentExemptReserve: number | bigint;
  authorized: AuthorizedArgs;
  lockup: LockupArgs;
};

export function getMetaSerializer(): Serializer<MetaArgs, Meta> {
  return struct<Meta>(
    [
      ['rentExemptReserve', u64()],
      ['authorized', getAuthorizedSerializer()],
      ['lockup', getLockupSerializer()],
    ],
    { description: 'Meta' }
  ) as Serializer<MetaArgs, Meta>;
}
